version: '3'
services:
  db:
    image: mysql:5.7
    container_name: appinio-db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    platform: linux/amd64
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: appinio-backend
    environment:
      - DATABASE_URL=mysql://user:password@appinio-db:3306/db
    stdin_open: true
    command:
      - /bin/bash
      - -c
      - |
        sleep 10
        npm run prisma-init
        npm run start:dev
    ports:
      - '8080:8080'
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./src:/app/src
