version: "3.8"

services:
  app:
    container_name: appinio-frontend
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
