# base image
FROM node:18-alpine as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package*.json ./
RUN npm install

RUN npm install react-scripts -g --silent

COPY . ./

# Expose port
EXPOSE 3000

# Start the app
CMD [ "npm", "start" ]